GET http://localhost:8080/dsHocsinh
###
GET http://127.0.0.1:8080/dsTivi

###
GET http://localhost:8080/dsDienthoai
###
GET http://localhost:8080/dsMathang
###
GET http://localhost:8080/Cuahang
###
POST http://localhost:8080/Dangnhap
Content-Type: application/json

{
    "Ten_Dang_nhap": "NV_100",
    "Mat_khau": "NV_1000"
}

###
POST http://localhost:8080/Lienhe
